version: "3"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_db
      MYSQL_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-data:


